//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceRequest.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustOffer
    {
        public int Id { get; set; }
        public int Price { get; set; }
        public string Term { get; set; }
        public int CustomersId { get; set; }
        public int OffersId { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Offer Offer { get; set; }
    }
}
